rootProject.name = "albaz"
include("albaz-di")
include("albaz-plugin")
include("albaz-application")
include("albaz-dispatch")
include("albaz-util")
include("albaz-cglib")
include("albaz-jcl")
include("albaz-common")
include("plugin-test")
include("albaz-dispatch-core")
include("albaz-dispatch-api")
